"""Tests for whisper credit stripping in text-cleaning module.

Covers French/English credit removal, edge cases for text that is
only a credit, and text without credit being returned unchanged.
"""

import sys
from pathlib import Path

_src = Path(__file__).parent.parent / "src"
if str(_src) not in sys.path:
    sys.path.insert(0, str(_src))

from whispy.core.audio import strip_whisper_credit
from whispy.core.text_cleaner import clean_text

# ---------------------------------------------------------------------------
# Hallucination phrase stripping (clean_text)
# ---------------------------------------------------------------------------


class TestHallucinationStripping:
    """Test that known Whisper hallucination phrases are stripped."""

    def test_amara_only_returns_empty(self):
        assert clean_text("Sous-titres réalisés par la communauté d'Amara.org") == ""

    def test_amara_short_form_only_returns_empty(self):
        assert clean_text("la communauté d'Amara.org") == ""

    def test_amara_case_insensitive(self):
        assert clean_text("LA COMMUNAUTÉ D'AMARA.ORG") == ""

    def test_amara_embedded_mid_text_removed(self):
        text = "Bonjour la communauté d'Amara.org merci"
        assert clean_text(text) == "Bonjour merci"

    def test_radio_canada_removed(self):
        assert clean_text("Sous-titrage Société Radio-Canada") == ""

    def test_merci_davoir_regarde_removed(self):
        assert clean_text("Merci d'avoir regardé cette vidéo") == ""

    def test_plain_text_unchanged(self):
        assert clean_text("Bonjour le monde") == "Bonjour le monde"

    def test_none_returns_none(self):
        assert clean_text(None) is None

    def test_empty_returns_empty(self):
        assert clean_text("") == ""

# ---------------------------------------------------------------------------
# French credit stripping
# ---------------------------------------------------------------------------


class TestFrenchCreditStripping:
    """Test that French Whisper credit prefixes are correctly stripped."""

    def test_sous_titres_realises_par_whisper(self):
        text = "Sous-titres réalisées par Whisper Hello world"
        assert strip_whisper_credit(text) == "Hello world"

    def test_sous_titres_realisees_par_whisper(self):
        text = "Sous-titres réalisées par Whisper Hello world"
        assert strip_whisper_credit(text) == "Hello world"

    def test_sous_titres_realisees_par_only(self):
        text = "Sous-titres réalisées par Whisper"
        assert strip_whisper_credit(text) == ""

    def test_sous_titres_generes_par_whisper(self):
        text = "Sous-titres générés par Whisper Bonjour"
        assert strip_whisper_credit(text) == "Bonjour"

    def test_sous_titres_par_whisper(self):
        text = "Sous-titres par Whisper Test"
        assert strip_whisper_credit(text) == "Test"


# ---------------------------------------------------------------------------
# English credit stripping
# ---------------------------------------------------------------------------


class TestEnglishCreditStripping:
    """Test that English Whisper credit prefixes are correctly stripped."""

    def test_subtitles_generated_by_whisper(self):
        text = "Subtitles generated by Whisper Hello world"
        assert strip_whisper_credit(text) == "Hello world"

    def test_subtitles_generated_by_whisper_only(self):
        text = "Subtitles generated by Whisper"
        assert strip_whisper_credit(text) == ""


# ---------------------------------------------------------------------------
# Text without credit
# ---------------------------------------------------------------------------


class TestTextWithoutCredit:
    """Test that text without credit is returned unchanged."""

    def test_plain_text_unchanged(self):
        text = "Hello world"
        assert strip_whisper_credit(text) == "Hello world"

    def test_french_text_unchanged(self):
        text = "Bonjour le monde"
        assert strip_whisper_credit(text) == "Bonjour le monde"

    def test_empty_string_returned_as_is(self):
        assert strip_whisper_credit("") == ""

    def test_none_like_empty(self):
        # strip_whisper_credit expects a string; None should not be passed
        # but we test empty string as the closest valid input
        assert strip_whisper_credit("") == ""


# ---------------------------------------------------------------------------
# Credit with trailing whitespace
# ---------------------------------------------------------------------------


class TestCreditWithTrailingWhitespace:
    """Test handling of credits with trailing whitespace."""

    def test_credit_with_trailing_space(self):
        text = "Sous-titres réalisées par Whisper "
        assert strip_whisper_credit(text) == ""

    def test_credit_with_multiple_trailing_spaces(self):
        text = "Sous-titres réalisées par Whisper   "
        assert strip_whisper_credit(text) == ""

    def test_credit_with_trailing_tab(self):
        text = "Sous-titres par Whisper\t"
        assert strip_whisper_credit(text) == ""

    def test_credit_with_trailing_newline(self):
        text = "Subtitles generated by Whisper\n"
        assert strip_whisper_credit(text) == ""


# ---------------------------------------------------------------------------
# Case insensitivity
# ---------------------------------------------------------------------------


class TestCaseInsensitivity:
    """Test that credit matching is case-insensitive."""

    def test_lowercase_whisper(self):
        text = "Sous-titres réalisées par whisper"
        assert strip_whisper_credit(text) == ""

    def test_mixed_case_subtitles(self):
        text = "SUBTITLES GENERATED BY WHISPER Hello"
        assert strip_whisper_credit(text) == "Hello"

    def test_mixed_case_sous_titres(self):
        text = "SOUS-TITRES RÉALISÉS PAR WHISPER Bonjour"
        assert strip_whisper_credit(text) == "Bonjour"


# ---------------------------------------------------------------------------
# Edge cases
# ---------------------------------------------------------------------------


class TestEdgeCases:
    """Test edge cases for credit stripping."""

    def test_text_only_contains_credit(self):
        """Text that only contains a credit returns empty string."""
        text = "Sous-titres réalisées par Whisper"
        assert strip_whisper_credit(text) == ""

    def test_credit_at_start_with_content_after(self):
        text = "Sous-titres réalisées par Whisper This is the actual content"
        assert strip_whisper_credit(text) == "This is the actual content"

    def test_sous_titres_generes_by_whisper_only(self):
        text = "Sous-titres générés par Whisper"
        assert strip_whisper_credit(text) == ""

    def test_english_credit_only(self):
        text = "Subtitles generated by Whisper"
        assert strip_whisper_credit(text) == ""
