"""Audio recording and transcription logic.

Handles audio capture via sox and transcription via faster-whisper,
integrating with the state machine for lifecycle management.
"""

import logging
import os
import re
import subprocess
import sys
import tempfile
import threading
import time
import wave
from pathlib import Path
from typing import Optional

from faster_whisper import WhisperModel

from .state_machine import State, StateMachine

logger = logging.getLogger(__name__)

# Regex to strip Whisper credit/watermark prefixes (French and English variants)
WHISPER_CREDIT_RE = re.compile(
    r"^(?:"
    r"Sous-titres\s+r(?:é|e)alis(?:é|e)s?(?:e?s)?\s+par\s*(?:Whisper\s*)?"
    r"|"
    r"Sous-titres\s+(?:g(?:é|e)n(?:é|e)r(?:é|e)e?s?\s+par\s+Whisper|par\s+Whisper)"
    r"|"
    r"Subtitles\s+generated\s+by\s+Whisper"
    r")",
    re.IGNORECASE,
)

RECORDING_PATH = os.path.join(tempfile.gettempdir(), "whispy.wav")


def strip_whisper_credit(text: str) -> str:
    """Remove Whisper credit/watermark prefixes from transcribed text.

    Strips French and English variants such as:
    - "Sous-titres réalisés par Whisper"
    - "Sous-titres générés par Whisper"
    - "Subtitles generated by Whisper"

    Returns the cleaned text, or empty string if the entire text was a credit.
    """
    if not text:
        return text
    cleaned = WHISPER_CREDIT_RE.sub("", text).strip()
    return cleaned

RECORDING_PATH = os.path.join(tempfile.gettempdir(), "whispy.wav")

# Minimum file size (bytes) indicating sox has started writing audio
_MIN_RECORDING_SIZE = 5120  # 5 KB
# Timeout for waiting for sox to become ready (seconds)
_RECORDING_READY_TIMEOUT = 2.0


class AudioEngine:
    """Manages audio recording and transcription operations.

    Integrates with the StateMachine to ensure proper lifecycle:
    IDLE -> RECORDING (start) -> TRANSCRIBING (stop) -> IDLE (complete)
    """

    def __init__(self, state_machine: StateMachine):
        self._sm = state_machine
        self._recording_process = None

    def start(self) -> bool:
        """Start recording audio. Returns False if already recording.

        Waits for sox to be ready and writing audio before returning,
        preventing the cold-start issue where the audio device needs
        time to wake up after idle.
        """
        if not self._sm.start_recording():
            return False

        self._recording_process = subprocess.Popen(
            ["sox", "-d", "-r", "16000", "-c", "1", RECORDING_PATH],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )

        self._wait_for_recording_ready()
        return True

    def _wait_for_recording_ready(self) -> None:
        """Wait for sox to start writing audio to the output file.

        Polls the file size until it exceeds _MIN_RECORDING_SIZE or
        the timeout expires. This handles the cold-start delay where
        the audio device takes time to initialize after being idle.
        """
        ready = threading.Event()
        stop_reason = [None]

        def _poll():
            start = time.monotonic()
            while not ready.is_set():
                if self._recording_process and self._recording_process.poll() is not None:
                    stop_reason[0] = "process_exited"
                    return
                try:
                    size = os.path.getsize(RECORDING_PATH)
                    if size >= _MIN_RECORDING_SIZE:
                        ready.set()
                        return
                except OSError:
                    pass
                if time.monotonic() - start > _RECORDING_READY_TIMEOUT:
                    stop_reason[0] = "timeout"
                    return
                time.sleep(0.02)

        threading.Thread(target=_poll, name="recording-waiter", daemon=True).start()
        ready.wait()
        if stop_reason[0] == "process_exited":
            logger.warning("[audio] Recording process exited before writing data")
        elif stop_reason[0] == "timeout":
            logger.warning(
                "[audio] Timeout waiting for recording to start — "
                "audio device may not be ready. First recording may be empty."
            )

    def stop(self) -> bool:
        """Stop recording and transition to TRANSCRIBING. Returns False if not recording."""
        if self._recording_process and self._recording_process.poll() is None:
            self._recording_process.terminate()
            try:
                self._recording_process.wait(timeout=2)
            except subprocess.TimeoutExpired:
                self._recording_process.kill()

        self._recording_process = None

        if os.path.exists(RECORDING_PATH):
            try:
                size = os.path.getsize(RECORDING_PATH)
                if size < _MIN_RECORDING_SIZE:
                    logger.warning(
                        f"[audio] Recording file too small ({size} bytes) — "
                        "sox may not have been ready when recording stopped. "
                        "Try pressing Fn again once the daemon is awake."
                    )
            except OSError:
                pass

        return self._sm.stop_recording()

    def transcribe(
        self,
        audio_path: str,
        model: Optional[WhisperModel],
        language: str = "auto",
        beam_size: int = 1,
        best_of: int = 2,
        auto_detect_min_duration: float = 0.5,
    ) -> Optional[str]:
        """Transcribe an audio file. Returns None if transcription fails."""
        if model is None:
            print(
                "[audio] Model not loaded, skipping transcription",
                file=sys.stderr,
            )
            return None

        # Detect audio duration for auto-detect language handling
        if language == "auto":
            duration = self._get_audio_duration(audio_path)
            if duration is not None and duration < auto_detect_min_duration:
                logger.warning(
                    "[audio] Audio too short (%.2fs < %.1fs) for reliable "
                    "auto-detect language. Proceeding with best effort.",
                    duration,
                    auto_detect_min_duration,
                )

        try:
            segments, _info = model.transcribe(
                audio_path,
                language=language,
                beam_size=beam_size,
                best_of=best_of,
            )
            text_parts = [seg.text.strip() for seg in segments]
            text = " ".join(text_parts)
            text = strip_whisper_credit(text)
            return text if text else None
        except Exception as exc:
            print(f"[audio] Transcription error: {exc}", file=sys.stderr)
            return None

    def _get_audio_duration(self, audio_path: str) -> Optional[float]:
        """Detect audio file duration in seconds using the wave module.

        Falls back to None if the file cannot be read as WAV.
        """
        try:
            with wave.open(audio_path, "rb") as wf:
                frames = wf.getnframes()
                rate = wf.getframerate()
                if rate > 0:
                    return frames / rate
        except (OSError, wave.Error):
            pass
        return None

    def cleanup_audio_file(self, audio_path: str = RECORDING_PATH) -> None:
        """Remove the temporary audio file after transcription."""
        try:
            if os.path.exists(audio_path):
                os.remove(audio_path)
        except OSError:
            pass

    def play_sound(self, sound_name: str = "Pop.aiff") -> None:
        """Play a system sound."""
        subprocess.Popen(
            ["afplay", f"/System/Library/Sounds/{sound_name}"],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )

    @property
    def is_recording(self) -> bool:
        return self._sm.is_recording

    @property
    def is_transcribing(self) -> bool:
        return self._sm.is_transcribing
