"""Text cleaning for Whisper transcription output.

Strips Whisper watermark credit phrases from the beginning of transcribed text,
preventing them from being injected into the active text field.
"""

import re

# French credit phrases (Whisper watermark)
_FRENCH_CREDITS = [
    "Sous-titres réalisées par Whisper",
    "Sous-titres réalisés par Whisper",
]

# English credit phrases (Whisper watermark)
_ENGLISH_CREDITS = [
    "Subtitles generated by Whisper",
    "Subtitles generated by whisper",
]

# Combined list, ordered longest-first to avoid partial matches
_ALL_CREDITS = sorted(
    _FRENCH_CREDITS + _ENGLISH_CREDITS,
    key=len,
    reverse=True,
)

# Compiled regex pattern for stripping credits
# Matches any credit phrase at the start of the string, followed by optional whitespace
_CREDIT_PATTERN = re.compile(
    r"^(" + "|".join(re.escape(c) for c in _ALL_CREDITS) + r")\s*",
    re.IGNORECASE,
)

# Known Whisper hallucination phrases (training-corpus artifacts) emitted on
# silence or near-empty audio. Unlike credits these can appear anywhere in the
# output, so they are stripped wherever they occur, not only as a prefix.
_HALLUCINATION_PHRASES = [
    "Sous-titres réalisés par la communauté d'Amara.org",
    "Sous-titrage Société Radio-Canada",
    "la communauté d'Amara.org",
    "Merci d'avoir regardé cette vidéo",
    "Merci d'avoir regardé la vidéo",
    "❤️ par SousTitreur.com",
    "par SousTitreur.com",
]

# Ordered longest-first so a longer phrase wins over a substring of itself.
_HALLUCINATION_PATTERN = re.compile(
    "|".join(
        re.escape(p)
        for p in sorted(_HALLUCINATION_PHRASES, key=len, reverse=True)
    ),
    re.IGNORECASE,
)


def clean_text(text: str | None) -> str | None:
    """Strip Whisper credit prefixes from transcribed text.

    Removes known Whisper watermark phrases (French and English) from the
    beginning of the text, along with any immediately following whitespace.

    Args:
        text: The raw transcribed text, or None.

    Returns:
        The cleaned text with credits stripped, or None/empty string:
        - If input is None, returns None.
        - If input is exactly a credit phrase (with optional trailing whitespace),
          returns "".
        - If no credit is found, returns the input unchanged.

    Examples:
        >>> clean_text("Sous-titres réalisées par Whisperbonjour")
        'bonjour'
        >>> clean_text("Sous-titres réalisées par Whisper")
        ''
        >>> clean_text("Sous-titres réalisées par Whisper  hello world")
        'hello world'
        >>> clean_text("Subtitles generated by Whisper test")
        'test'
        >>> clean_text("Hello world")
        'Hello world'
        >>> clean_text(None) is None
        True
        >>> clean_text("")
        ''
    """
    if text is None:
        return None

    if not text:
        return ""

    cleaned = _CREDIT_PATTERN.sub("", text)
    # Strip known hallucination phrases anywhere in the text, then collapse the
    # whitespace they leave behind. If nothing meaningful remains, return "".
    cleaned = _HALLUCINATION_PATTERN.sub(" ", cleaned)
    cleaned = re.sub(r"\s+", " ", cleaned).strip()
    return cleaned
