"""Text cleaning for Whisper transcription output.

Strips Whisper watermark credit phrases from the beginning of transcribed text,
preventing them from being injected into the active text field.
"""

import re
from typing import Optional

# French credit phrases (Whisper watermark)
_FRENCH_CREDITS = [
    "Sous-titres réalisées par Whisper",
    "Sous-titres réalisés par Whisper",
]

# English credit phrases (Whisper watermark)
_ENGLISH_CREDITS = [
    "Subtitles generated by Whisper",
    "Subtitles generated by whisper",
]

# Combined list, ordered longest-first to avoid partial matches
_ALL_CREDITS = sorted(
    _FRENCH_CREDITS + _ENGLISH_CREDITS,
    key=len,
    reverse=True,
)

# Compiled regex pattern for stripping credits
# Matches any credit phrase at the start of the string, followed by optional whitespace
_CREDIT_PATTERN = re.compile(
    r"^(" + "|".join(re.escape(c) for c in _ALL_CREDITS) + r")\s*",
    re.IGNORECASE,
)


def clean_text(text: Optional[str]) -> Optional[str]:
    """Strip Whisper credit prefixes from transcribed text.

    Removes known Whisper watermark phrases (French and English) from the
    beginning of the text, along with any immediately following whitespace.

    Args:
        text: The raw transcribed text, or None.

    Returns:
        The cleaned text with credits stripped, or None/empty string:
        - If input is None, returns None.
        - If input is exactly a credit phrase (with optional trailing whitespace),
          returns "".
        - If no credit is found, returns the input unchanged.

    Examples:
        >>> clean_text("Sous-titres réalisées par Whisperbonjour")
        'bonjour'
        >>> clean_text("Sous-titres réalisées par Whisper")
        ''
        >>> clean_text("Sous-titres réalisées par Whisper  hello world")
        'hello world'
        >>> clean_text("Subtitles generated by Whisper test")
        'test'
        >>> clean_text("Hello world")
        'Hello world'
        >>> clean_text(None) is None
        True
        >>> clean_text("")
        ''
    """
    if text is None:
        return None

    if not text:
        return ""

    cleaned = _CREDIT_PATTERN.sub("", text)
    return cleaned
