"""Live-drive layer: boot the REAL daemon and drive it over HTTP — no mocks.

The daemon is launched as a fresh subprocess (`whispy_daemon.py --headless`) so
the test suite's global Quartz/rumps/audio mocks (set up in `conftest.py`) do
NOT apply — the same clean-subprocess pattern the live event-tap smoke test
already uses. The harness polls `GET /status` for readiness, drives a
`POST /start` → wait → `POST /stop` cycle, and reads `GET /last-transcription`,
classifying every check as PASS / FAIL / UNVERIFIED.

Tier: live-driven. An absent mic/model/permission or a daemon that will not boot
surfaces as UNVERIFIED, never a silent pass.
"""

from __future__ import annotations

import json
import os
import queue
import re
import shutil
import subprocess
import sys
import tempfile
import threading
import time
import urllib.error
import urllib.request
from contextlib import contextmanager
from pathlib import Path

from .outcomes import CheckResult, Outcome

REPO_ROOT = Path(__file__).resolve().parents[2]
DAEMON = REPO_ROOT / "whispy_daemon.py"
SRC = REPO_ROOT / "src"
FIXTURES = REPO_ROOT / "tests" / "fixtures" / "audio"
USER_CONFIG = Path.home() / ".config" / "whispy" / "config.json"
READY_PREFIX = "WHISPY_HEADLESS_READY"

# Deterministic speech fixtures → (language, expected tokens that MUST appear).
# Phrases are generated by tests/fixtures/audio/generate.sh; keep in sync.
SPEECH_FIXTURES = {
    "fr": ("fr_speech.wav", ["test", "fini"]),
    "en": ("en_speech.wav", ["testing", "done"]),
}


# The per-install API token of the daemon under drive. Set by
# boot_headless_daemon once the throwaway daemon has created it; every _http
# call authenticates with it (the API rejects unauthenticated callers).
_AUTH_TOKEN: str | None = None


def _http(method: str, url: str, timeout: float, body: dict | None = None) -> dict:
    data = json.dumps(body).encode() if body is not None else None
    req = urllib.request.Request(url, data=data, method=method)
    if data is not None:
        req.add_header("Content-Type", "application/json")
    if _AUTH_TOKEN:
        req.add_header("Authorization", f"Bearer {_AUTH_TOKEN}")
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        raw = resp.read().decode() or "{}"
    return json.loads(raw)


@contextmanager
def boot_headless_daemon(boot_timeout: float = 30.0):
    """Boot the real daemon headless; yield (proc, base_url) or (None, None).

    Yields (None, None) when the daemon cannot boot or never reports ready —
    the caller turns that into UNVERIFIED. Always tears the subprocess down.

    Runs against a throwaway config (a copy of the user's, or defaults) via
    WHISPY_CONFIG so driving language/model over the API never mutates the real
    config file.
    """
    tmp_cfg = tempfile.NamedTemporaryFile(prefix="whispy-validate-", suffix=".json", delete=False)
    tmp_cfg.close()
    if USER_CONFIG.exists():
        shutil.copy(USER_CONFIG, tmp_cfg.name)
    else:
        Path(tmp_cfg.name).unlink(missing_ok=True)  # absent → daemon uses defaults

    # Pin the transcribe-file allow-dir to the committed fixtures so the
    # deterministic POST /transcribe-file checks are accepted by the API's
    # path allow-list, wherever the harness runs from.
    env = dict(
        os.environ,
        PYTHONPATH=str(SRC),
        WHISPY_CONFIG=tmp_cfg.name,
        WHISPY_TRANSCRIBE_DIR=str(FIXTURES),
    )
    proc = subprocess.Popen(
        [sys.executable, str(DAEMON), "--headless"],
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        env=env,
        bufsize=1,
    )

    # Read stdout on a thread so we can wait for readiness with a deadline.
    lines: queue.Queue[str] = queue.Queue()

    def _pump():
        assert proc.stdout is not None
        for line in proc.stdout:
            lines.put(line.rstrip("\n"))

    threading.Thread(target=_pump, daemon=True).start()

    base_url = None
    deadline = time.monotonic() + boot_timeout
    try:
        while time.monotonic() < deadline:
            if proc.poll() is not None:
                break  # died during boot
            try:
                line = lines.get(timeout=0.25)
            except queue.Empty:
                continue
            if line.startswith(READY_PREFIX):
                port = int(line.split()[-1])
                base_url = f"http://127.0.0.1:{port}"
                # The daemon created its token before reporting ready; read it
                # from the throwaway config so every _http call authenticates.
                global _AUTH_TOKEN
                from whispy.core.auth import read_token

                _AUTH_TOKEN = read_token(Path(tmp_cfg.name))
                break
        yield (proc, base_url) if base_url else (None, None)
    finally:
        if proc.poll() is None:
            proc.terminate()
            try:
                proc.wait(timeout=10)
            except subprocess.TimeoutExpired:
                proc.kill()
        Path(tmp_cfg.name).unlink(missing_ok=True)


def _wait_status(base_url: str, deadline: float) -> dict | None:
    """Poll GET /status until reachable or deadline; None on timeout."""
    while time.monotonic() < deadline:
        try:
            return _http("GET", f"{base_url}/status", timeout=2)
        except (urllib.error.URLError, OSError):
            time.sleep(0.25)
    return None


def _wait_model(base_url: str, deadline: float) -> bool:
    """Poll GET /status until the Whisper model is loaded; False on timeout."""
    while time.monotonic() < deadline:
        try:
            if _http("GET", f"{base_url}/status", timeout=2).get("model_loaded"):
                return True
        except (urllib.error.URLError, OSError):
            pass
        time.sleep(0.5)
    return False


def _tokens(text: str) -> set[str]:
    """Normalize transcription to a set of lowercase alphanumeric tokens."""
    return set(re.findall(r"[a-z0-9]+", (text or "").lower()))


def run_semantic_checks(base_url: str) -> list[CheckResult]:
    """Deterministic transcription checks against committed WAV fixtures.

    Drives `POST /transcribe-file` (real model, current config, no mic, no
    injection) on known audio: silence → empty, and per-language speech →
    expected tokens. Language is switched via `POST /config` on the throwaway
    config. UNVERIFIED when the model never loads (e.g. not cached, offline).
    """
    plat = sys.platform
    out: list[CheckResult] = []

    if not _wait_model(base_url, time.monotonic() + 120):
        return [
            CheckResult(
                "Transcription of known speech",
                Outcome.UNVERIFIED,
                "model never loaded (not cached / offline?)",
                tier="live-driven",
                platform=plat,
            )
        ]

    # Config change applies over HTTP (drives the same path the menu/tray use).
    try:
        _http("POST", f"{base_url}/config", timeout=10, body={"language": "en"})
        applied = _http("GET", f"{base_url}/config", timeout=5).get("language")
        out.append(
            CheckResult(
                "Config change applies over HTTP",
                Outcome.PASS if applied == "en" else Outcome.FAIL,
                "language set to 'en' and reflected" if applied == "en" else f"language not applied: {applied!r}",
                tier="live-driven",
                platform=plat,
            )
        )
    except (urllib.error.URLError, OSError) as exc:
        out.append(
            CheckResult(
                "Config change applies over HTTP",
                Outcome.FAIL,
                f"/config drive failed: {exc}",
                tier="live-driven",
                platform=plat,
            )
        )

    # Negative control: silence must NOT yield speech tokens.
    silence = FIXTURES / "silence.wav"
    if silence.exists():
        try:
            text = (
                _http("POST", f"{base_url}/transcribe-file", timeout=120, body={"path": str(silence)}).get("text") or ""
            )
            empty = not _tokens(text)
            out.append(
                CheckResult(
                    "Silence yields empty transcription",
                    Outcome.PASS if empty else Outcome.FAIL,
                    "no speech detected in silence" if empty else f"unexpected text from silence: {text!r}",
                    tier="live-driven",
                    platform=plat,
                )
            )
        except (urllib.error.URLError, OSError) as exc:
            out.append(
                CheckResult(
                    "Silence yields empty transcription",
                    Outcome.FAIL,
                    f"/transcribe-file failed: {exc}",
                    tier="live-driven",
                    platform=plat,
                )
            )

    # Positive, per-language: known speech → expected tokens, in that language.
    for lang, (fname, expected) in SPEECH_FIXTURES.items():
        wav = FIXTURES / fname
        if not wav.exists():
            out.append(
                CheckResult(
                    f"Transcription of known speech ({lang})",
                    Outcome.UNVERIFIED,
                    f"fixture missing: {fname} (run tests/fixtures/audio/generate.sh)",
                    tier="live-driven",
                    platform=plat,
                )
            )
            continue
        try:
            _http("POST", f"{base_url}/config", timeout=10, body={"language": lang})
            text = _http("POST", f"{base_url}/transcribe-file", timeout=120, body={"path": str(wav)}).get("text") or ""
        except (urllib.error.URLError, OSError) as exc:
            out.append(
                CheckResult(
                    f"Transcription of known speech ({lang})",
                    Outcome.FAIL,
                    f"drive failed: {exc}",
                    tier="live-driven",
                    platform=plat,
                )
            )
            continue
        got = _tokens(text)
        missing = [t for t in expected if t not in got]
        out.append(
            CheckResult(
                f"Transcription of known speech ({lang})",
                Outcome.PASS if not missing else Outcome.FAIL,
                f"got {text!r}" if not missing else f"missing {missing} in {text!r} (language={lang})",
                tier="live-driven",
                platform=plat,
            )
        )
    return out


def _build_multi_utterance_wav(dest: Path) -> bool:
    """Concatenate fr_speech + silence + fr_speech into ``dest`` (under allow-dir).

    Two utterances split by the committed 1 s silence gap → the streaming
    segmenter must cut on that pause and yield ≥2 chunks. Returns False if the
    source fixtures are missing.
    """
    import wave

    fr = FIXTURES / "fr_speech.wav"
    sil = FIXTURES / "silence.wav"
    if not fr.exists() or not sil.exists():
        return False
    with wave.open(str(fr), "rb") as w:
        params = w.getparams()
        fr_frames = w.readframes(w.getnframes())
    with wave.open(str(sil), "rb") as w:
        sil_frames = w.readframes(w.getnframes())
    with wave.open(str(dest), "wb") as w:
        w.setparams(params)
        w.writeframes(fr_frames)
        w.writeframes(sil_frames)
        w.writeframes(fr_frames)
    return True


def run_streaming_checks(base_url: str) -> list[CheckResult]:
    """Deterministic streaming checks over ``POST /stream-file`` (no mic).

    Proves the live segmentation + per-chunk transcription wiring end to end:
    a known utterance streams to the expected tokens, and a two-utterance clip
    split by a silence gap is cut into ≥2 chunks. UNVERIFIED when the model never
    loads.
    """
    plat = sys.platform
    out: list[CheckResult] = []

    if not _wait_model(base_url, time.monotonic() + 120):
        return [
            CheckResult(
                "Streaming chunk transcription (HTTP)",
                Outcome.UNVERIFIED,
                "model never loaded (not cached / offline?)",
                tier="live-driven",
                platform=plat,
            )
        ]

    # 1. Known speech streams to the expected tokens (proves the seam transcribes).
    fr = FIXTURES / "fr_speech.wav"
    if fr.exists():
        try:
            _http("POST", f"{base_url}/config", timeout=10, body={"language": "fr"})
            resp = _http("POST", f"{base_url}/stream-file", timeout=120, body={"path": str(fr)})
            texts = resp.get("texts") or []
            got = _tokens(resp.get("text") or "")
            missing = [t for t in ("test", "fini") if t not in got]
            ok = texts and not missing
            out.append(
                CheckResult(
                    "Streaming chunk transcription (HTTP)",
                    Outcome.PASS if ok else Outcome.FAIL,
                    f"{len(texts)} chunk(s), text={resp.get('text')!r}"
                    if ok
                    else f"missing {missing} / no chunks: {resp!r}",
                    tier="live-driven",
                    platform=plat,
                )
            )
        except (urllib.error.URLError, OSError) as exc:
            out.append(
                CheckResult(
                    "Streaming chunk transcription (HTTP)",
                    Outcome.FAIL,
                    f"/stream-file drive failed: {exc}",
                    tier="live-driven",
                    platform=plat,
                )
            )

    # 2. A two-utterance clip split by silence is segmented into ≥2 chunks.
    multi = FIXTURES / "_stream_multi_tmp.wav"
    if _build_multi_utterance_wav(multi):
        try:
            _http("POST", f"{base_url}/config", timeout=10, body={"language": "fr"})
            resp = _http("POST", f"{base_url}/stream-file", timeout=120, body={"path": str(multi)})
            texts = resp.get("texts") or []
            out.append(
                CheckResult(
                    "Streaming segments on silence (≥2 chunks)",
                    Outcome.PASS if len(texts) >= 2 else Outcome.FAIL,
                    f"{len(texts)} chunks: {texts!r}"
                    if len(texts) >= 2
                    else f"expected ≥2 chunks, got {len(texts)}: {texts!r}",
                    tier="live-driven",
                    platform=plat,
                )
            )
        except (urllib.error.URLError, OSError) as exc:
            out.append(
                CheckResult(
                    "Streaming segments on silence (≥2 chunks)",
                    Outcome.FAIL,
                    f"/stream-file drive failed: {exc}",
                    tier="live-driven",
                    platform=plat,
                )
            )
        finally:
            multi.unlink(missing_ok=True)
    return out


def drive_cycle(base_url: str, record_seconds: float = 1.0) -> list[CheckResult]:
    """Drive a record→transcribe cycle over HTTP and classify the results."""
    plat = sys.platform
    results: list[CheckResult] = []

    status = _wait_status(base_url, time.monotonic() + 10)
    if status is None:
        return [
            CheckResult(
                "Driven record→transcribe cycle (HTTP)",
                Outcome.UNVERIFIED,
                "daemon /status never became reachable",
                tier="live-driven",
                platform=plat,
            )
        ]

    # POST /start — expect recording to begin.
    try:
        _http("POST", f"{base_url}/start", timeout=10)
        time.sleep(0.3)
        recording = _http("GET", f"{base_url}/status", timeout=5).get("is_recording")
    except (urllib.error.URLError, OSError) as exc:
        return [
            CheckResult(
                "Driven record→transcribe cycle (HTTP)",
                Outcome.UNVERIFIED,
                f"/start failed (no input device?): {exc}",
                tier="live-driven",
                platform=plat,
            )
        ]

    if not recording:
        results.append(
            CheckResult(
                "Driven record→transcribe cycle (HTTP)",
                Outcome.UNVERIFIED,
                "recording did not start (mic unavailable / permission?)",
                tier="live-driven",
                platform=plat,
            )
        )
        return results

    time.sleep(record_seconds)

    # POST /stop runs transcription synchronously; give the model room to load.
    try:
        stop = _http("POST", f"{base_url}/stop", timeout=300)
        post = _http("GET", f"{base_url}/status", timeout=5)
        last = _http("GET", f"{base_url}/last-transcription", timeout=5)
    except (urllib.error.URLError, OSError, json.JSONDecodeError) as exc:
        return [
            CheckResult(
                "Driven record→transcribe cycle (HTTP)",
                Outcome.FAIL,
                f"/stop or status read failed mid-cycle: {exc}",
                tier="live-driven",
                platform=plat,
            )
        ]

    # The pipeline ran end to end if the FSM returned to idle.
    transitions_ok = post.get("is_recording") is False and post.get("is_transcribing") is False
    results.append(
        CheckResult(
            "Driven record→transcribe cycle (HTTP)",
            Outcome.PASS if transitions_ok else Outcome.FAIL,
            "start→stop transitioned recording→idle" if transitions_ok else f"unexpected post-stop status: {post}",
            tier="live-driven",
            platform=plat,
        )
    )

    # Content is a separate check: empty text unattended usually means silence
    # (no speech), which is UNVERIFIED, not a failure.
    text = (last.get("text") or stop.get("text") or "").strip()
    if text:
        results.append(
            CheckResult(
                "Transcription yields text",
                Outcome.PASS,
                f"{len(text)} chars transcribed",
                tier="live-driven",
                platform=plat,
            )
        )
    else:
        results.append(
            CheckResult(
                "Transcription yields text",
                Outcome.UNVERIFIED,
                "empty (silence) — live mic content is operator-verified; "
                "deterministic content is covered by the fixture checks below",
                tier="live-driven",
                platform=plat,
            )
        )
    return results


def run_live_drive(record_seconds: float = 1.0) -> list[CheckResult]:
    """Boot the real daemon once; run the mic cycle + deterministic fixture checks.

    The mic cycle proves the real record→transcribe pipeline (UNVERIFIED if no
    device/speech). The fixture checks prove transcription *content* and language
    selection deterministically over `POST /transcribe-file`. UNVERIFIED if the
    daemon won't boot.
    """
    with boot_headless_daemon() as (proc, base_url):
        if base_url is None:
            return [
                CheckResult(
                    "Driven record→transcribe cycle (HTTP)",
                    Outcome.UNVERIFIED,
                    "headless daemon did not boot (missing deps/permissions?)",
                    tier="live-driven",
                    platform=sys.platform,
                )
            ]
        results = drive_cycle(base_url, record_seconds=record_seconds)
        results.extend(run_semantic_checks(base_url))
        results.extend(run_streaming_checks(base_url))
        return results
